### PR TITLE
Make {{url}} available in overlay templates

### PR DESCRIPTION
**Pull request by fredvd**
so you can put a link to a carousel item.

### CODE REVIEW

**Comment by hvelarde** [comment]
tests are failing, do you know why?

**Comment by fredvd** [comment]
I looked at it for a while on friday afternoon but I think its a CI issue. The other pull requests are failing to, all on an element nog showing in the caroussel after 30 seconds, but a local bin/test runs all the robot tests just fine with collective.js.cycle2 pinned to a1.

I compared  collective.cover CI setup with this tile and noticed that c.cover uploads artefacts to s3 if the build goes wrong. Can we add that here as well to get more feedback?

**Comment by hvelarde** [comment]
I can check that but not now

**Comment by fredvd** [comment]
Close this pull request, too much rebasing for one simple template variable, will readd it later.

**Pull request closed without merging**
